INSERT INTO cousines (id, name) VALUES
  (1, 'Chinese'),
  (2, 'Pizza'),
  (3, 'Vietnamese'),
  (4, 'Sushi');

INSERT INTO stores (id, name, address, cousine_id) VALUES
  (1, 'Hai Shang', '2991 Pembina Hwy, Winnipeg, Manitoba R3T 2H5, Canada', 1),
  (2, 'Ye''s', 'St James St, Winnipeg, Manitoba R3G 3J5, Canada', 1),
  (3, 'Good Earth Chop Suey House', '1849 Portage Ave, Winnipeg, Manitoba R3J 0G8, Canada', 1),
  (4, 'Za Pizza Bistro',  'Mary''s Rd, Winnipeg, Manitoba R2M 3V6, Canada', 2),
  (5, 'Santa Lucia Pizza Winnipeg',  'Mary''s Rd, Winnipeg, Manitoba R2H 1H1, Canada', 2),
  (6, 'Carbone Coal Fired Pizza', '1580 Taylor Avenue, Winnipeg Manitoba R3N 2A7, Canada', 2),
  (7, 'Pho Kim Tuong', '856 Ellice Ave, Winnipeg, Manitoba R3G 0C4, Canada', 3),
  (8, 'Pho Hoang', '794 Sargent Ave, Winnipeg, Manitoba R3E 0B7, Canada', 3),
  (9, 'Viva Restaurant', '505 Sargent Ave, Winnipeg, Manitoba R3B 1V9, Canada', 3),
  (10, 'Blufish', '179 Bannatyne Ave, Winnipeg, Manitoba R3B 0R4, Canada', 4),
  (11, 'Wasabi Sabi', 'Taylor Avenue, Winnipeg, Manitoba, Canada', 4),
  (12, 'Sushi N', '726 St Anne''s Rd, Southglen Shopping Mall', 4);

INSERT INTO products (id, store_id, name, description, price) VALUES 
  (1, 1, 'Shrimp Tempura', 'Fresh shrimp battered and deep fried until golden brown', 10.95),
  (2, 1, 'Shrimp with Snow Peas and Cashew', 'A delicious combination of fresh shrimp, snow peas, and cashew', 12.5),
  (3, 1, 'Special Deep-Fried Fish', 'Tilapia fish deep fried until flaky and tender', 12.95),
  (4, 2, 'BBQ Pork Egg Foo Yung', 'Chinese omelette filled with barbequed pork', 10.95),
  (5, 2, 'Beef Egg Foo Yung', 'A Chinese omelette mixed with beef', 10.95),
  (6, 2, 'Mushroom Egg Foo Yung', 'A Chinese omelette mixed with sliced mushrooms', 9.95),
  (7, 3, 'BBQ Pork, Chicken, or Mushroom Chop Suey', '', 8.75),
  (8, 3, 'Deluxe Chop Suey', 'Shrimp, barbeque pork, and chicken', 9.95),
  (9, 3, 'Plain Fried Rice', '', 7.5),
  (10, 4, '10" Small Greek Pizza', 'Green or black olives, onions, tomato, and feta cheese', 8.99),
  (11, 4, '12" Medium Deluxe Pizza', 'Pepperoni, bacon, mushrooms, onions, and green peppers', 12.99),
  (12, 4, 'Pizza and Wings Special', 'One twelve-inch medium pizza with two toppings and twelve chicken wings', 16.99),
  (13, 5, '10" Garden Fresh Pizza', 'Green peppers, onions, mushrooms, black olives, and Roma tomatoes', 14),
  (14, 5, '12" Tuscan Six-Cheese Pizza', 'An authentic blend of Parmesan, Romano, Asiago, fontina, provolone, and 100% real cheese made from mozzarella', 19),
  (15, 5, '14" Hawaiian Chicken Pizza', 'A sweet and savory combination of juicy pineapple and grilled chicken', 22),
  (16, 6, 'Medium One-Topping Pie', 'A 12-inch, medium pizza made of famous, fresh, house-made dough, cooked with one topping of your choice', 15),
  (17, 6, 'X-Large One-Topping Pie', 'An extra large, 16-inch pizza made of famous, fresh, house-made dough, cooked with one topping of your choice', 23),
  (18, 6, 'Medium BBQ Pulled Pork Pie', 'A 12-inch pizza made of famous, fresh, and house-made dough, topped with Caribbean jerk chicken, pineapple, onions, feta, and mozzarella cheese', 19),
  (19, 7, 'Pork Spring Roll (6 pcs) - Cha Gio (6 Cuon)', 'Served with fish sauce. One order comes with six spring rolls', 7.5),
  (20, 7, 'Butterfly Shrimp - Tom Chien', 'Served with sweet chilli sauce', 10.5),
  (21, 7, 'Deluxe Wonton Soup (15 pcs) - Hoanh Thanh Sup Thap Cam (15)', 'One order comes with fifteen wontons', 10.35),
  (22, 8, 'Grilled Pork Skewers (2 pcs)', 'House-marinated ground pork skewers with roasted peanuts and bacon. One order comes with two skewers', 5.75),
  (23, 8, 'Chicken Wang-Yo!', 'Stuffed minced chicken, carrot, green onions, mushrooms, black pepper, and bean thread noodles', 9.95),
  (24, 8, 'Beef Stew', 'Beef flank, carrot, jumbo onion, scallions, cilantro, mint, and Thai basil. Served with a side of baguette and broth', 8.75),
  (25, 9, 'Tripe and Flank Pho - Nam Long', 'A tasty blend of beef tripe and flank served in a steaming-hot rice noodle soup', 8.99),
  (26, 9, 'Charbroiled Pork - Thit Nuong', 'Tender charbroiled pork served atop a bed of vermicelli noodles with iceberg lettuce, bean sprouts, cucumbers, pickled and radish', 9.99),
  (27, 9, 'Charbroiled Beef - Bo Nuong', 'Savoury charbroiled beef served atop a bed of vermicelli noodles with iceberg lettuce, bean sprouts, cucumbers, pickled carrot',  10.49),
  (28, 10, 'Assorted Sashimi', 'Fresh assorted sashimi, hand-picked and thinly sliced by the chef', 20),
  (29, 10, 'Sake (Salmon) Sashimi', 'Thinly sliced raw salmon served on its own', 9),
  (30, 10, 'Red Tuna Sashimi', 'Thinly sliced red tuna, served without rice', 13),
  (31, 11, 'Ebi - Nigiri (1 pc)', 'Steamed shrimp, served on a small bed of pressed sushi rice. One order comes with one piece', 2.5),
  (32, 11, 'Hamachi - Nigiri (1 pc)', 'Thinly sliced yellowtail served on a small bed of pressed sushi rice. One order comes with one piece', 3.5),
  (33, 11, 'Ika - Nigiri (1 pc)', 'Thin-sliced squid served on a small bed of pressed sushi rice. One order comes with one piece', 2.5),
  (34, 12, 'Salmon Sushi (2 pcs)', 'Fresh, raw salmon wrapped with rice and seaweed. One order comes with two pieces', 5.45),
  (35, 12, 'Masago Sushi (2 pcs)', 'Red caviar wrapped with rice and seaweed. One order comes with two pieces', 4.75),
  (36, 12, 'Amaebi Sushi (2 pcs)', 'Sweet shrimp wrapped in rice and seaweed. One order comes with two pieces', 5.75);